version: "3.3"

services:
  ################### Backend #########################
  app:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:3000
    restart: always
    depends_on:
      - db
  ################### GUI para MySQL #########################
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db
  ################### Base de Datos #########################
  db:
    build:
      context: ./database/
      dockerfile: Dockerfile
    container_name: database
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw    